version: "3.9"  # optional since v1.27.0

services:
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data # name of volume:name of location storage
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_DB: ${USER}
      POSTGRES_PASSWORD: ${USER}
  web:
    build: .
    command: python edom_backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_DB: ${USER}
      POSTGRES_PASSWORD: ${USER}
    depends_on:
      - db
